pipeline {
    agent any

    stages {

        stage('Install dependencies') {
            steps {
                bat """
                pip install -r Frames\\requirements.txt
                """
            }
        }

        stage('Run Tests') {
            steps {
                bat """
                pytest -s -v --browser_name=headless  Frames\\Test\\test_google.py
                """
            }
        }
    }
}
